// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreBookStore.Data.EF;

namespace NetCoreBookStore.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200731232237_ShoppingCartAdded")]
    partial class ShoppingCartAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a40bcfd4-4acf-45b1-9472-ec3b56483299"),
                            RoleId = new Guid("a40bcfd4-4acf-45b1-9472-ec3b56483299")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a40bcfd4-4acf-45b1-9472-ec3b56483299"),
                            ConcurrencyStamp = "e5cd344a-e550-4e2d-9778-ea41834dc307",
                            Description = "Admin role",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a40bcfd4-4acf-45b1-9472-ec3b56483299"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "724ae484-e0d5-4b73-b264-e6345205ba52",
                            Dob = new DateTime(2020, 8, 1, 6, 22, 36, 264, DateTimeKind.Local).AddTicks(494),
                            Email = "app-admin@abc.xyz",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "app-admin@abc.xyz",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEOfc/VrUfBOQCcIBbM94m79vZBRufQZYLdN3KTfss9pjjVwTVOUYWnDEejvHsECzHg==",
                            PhoneNumber = "0985123745",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("NameAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = "9bb6c949-1bea-48a6-94a0-f2c4b1614b81",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 246, DateTimeKind.Local).AddTicks(1815),
                            Description = "<p>Book 1 is simply dummy text of the printing and typesetting industry. Book 1 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 1 has been the book. </p><p>Book 1's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-1",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 247, DateTimeKind.Local).AddTicks(955),
                            Status = 1,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = "446d4499-bd54-46e1-b93f-45b7e38101e1",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(15),
                            Description = "<p>Book 5 is simply dummy text of the printing and typesetting industry. Book 5 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 5 has been the book. </p><p>Book 5's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-5",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(31),
                            Status = 1,
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = "60300f7c-2afd-4309-882e-0e821bfbfed0",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(291),
                            Description = "<p>Book 9 is simply dummy text of the printing and typesetting industry. Book 9 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 9 has been the book. </p><p>Book 9's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-9",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(293),
                            Status = 1,
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = "6fbc53ee-78f0-4f73-a7f7-ec42084e1a2c",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(340),
                            Description = "<p>Book 13 is simply dummy text of the printing and typesetting industry. Book 13 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 13 has been the book. </p><p>Book 13's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-13",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(342),
                            Status = 1,
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = "8fc1ddfe-4880-4ff8-b265-0e6f57afc1c1",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(387),
                            Description = "<p>Book 17 is simply dummy text of the printing and typesetting industry. Book 17 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 17 has been the book. </p><p>Book 17's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-17",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(388),
                            Status = 1,
                            Title = "Book 17"
                        },
                        new
                        {
                            Id = "c0750072-426c-44cd-92d7-39bd02c71cf0",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(429),
                            Description = "<p>Book 21 is simply dummy text of the printing and typesetting industry. Book 21 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 21 has been the book. </p><p>Book 21's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-21",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(430),
                            Status = 1,
                            Title = "Book 21"
                        },
                        new
                        {
                            Id = "d6981c48-11c1-41d6-be9e-cf2a60dda2c6",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(521),
                            Description = "<p>Book 25 is simply dummy text of the printing and typesetting industry. Book 25 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 25 has been the book. </p><p>Book 25's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-25",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(522),
                            Status = 1,
                            Title = "Book 25"
                        },
                        new
                        {
                            Id = "80a14e57-b9a4-47e9-9144-627e5b1668ee",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(563),
                            Description = "<p>Book 29 is simply dummy text of the printing and typesetting industry. Book 29 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 29 has been the book. </p><p>Book 29's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-29",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(564),
                            Status = 1,
                            Title = "Book 29"
                        },
                        new
                        {
                            Id = "ff2d5ebc-7a8f-467b-a983-357f33693840",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(606),
                            Description = "<p>Book 33 is simply dummy text of the printing and typesetting industry. Book 33 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 33 has been the book. </p><p>Book 33's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-33",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(608),
                            Status = 1,
                            Title = "Book 33"
                        },
                        new
                        {
                            Id = "749ca424-9791-4693-a85a-0e1c955ac5f9",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(647),
                            Description = "<p>Book 37 is simply dummy text of the printing and typesetting industry. Book 37 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 37 has been the book. </p><p>Book 37's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-37",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(648),
                            Status = 1,
                            Title = "Book 37"
                        },
                        new
                        {
                            Id = "8d8bea9a-7125-49ec-99e9-1596eb1058f8",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(758),
                            Description = "<p>Book 41 is simply dummy text of the printing and typesetting industry. Book 41 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 41 has been the book. </p><p>Book 41's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-41",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(760),
                            Status = 1,
                            Title = "Book 41"
                        },
                        new
                        {
                            Id = "a10023f7-a765-4782-bc89-4891c2bc90dd",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(803),
                            Description = "<p>Book 45 is simply dummy text of the printing and typesetting industry. Book 45 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 45 has been the book. </p><p>Book 45's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-45",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(804),
                            Status = 1,
                            Title = "Book 45"
                        },
                        new
                        {
                            Id = "376cebea-4428-4746-8376-2055cd19c285",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(846),
                            Description = "<p>Book 49 is simply dummy text of the printing and typesetting industry. Book 49 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 49 has been the book. </p><p>Book 49's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-49",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(847),
                            Status = 1,
                            Title = "Book 49"
                        },
                        new
                        {
                            Id = "e5db32f1-4e3a-489e-b22f-c4b2c415949f",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(885),
                            Description = "<p>Book 53 is simply dummy text of the printing and typesetting industry. Book 53 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 53 has been the book. </p><p>Book 53's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-53",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(886),
                            Status = 1,
                            Title = "Book 53"
                        },
                        new
                        {
                            Id = "419ea699-6f65-4918-9aa6-183bf61f3ab2",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(959),
                            Description = "<p>Book 57 is simply dummy text of the printing and typesetting industry. Book 57 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 57 has been the book. </p><p>Book 57's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-57",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(960),
                            Status = 1,
                            Title = "Book 57"
                        },
                        new
                        {
                            Id = "e2d9cf0c-baa4-464b-9071-17db23fc3557",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1001),
                            Description = "<p>Book 61 is simply dummy text of the printing and typesetting industry. Book 61 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 61 has been the book. </p><p>Book 61's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-61",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1002),
                            Status = 1,
                            Title = "Book 61"
                        },
                        new
                        {
                            Id = "139dc314-c48d-4713-86ad-b51f83daed0c",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1044),
                            Description = "<p>Book 65 is simply dummy text of the printing and typesetting industry. Book 65 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 65 has been the book. </p><p>Book 65's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-65",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1045),
                            Status = 1,
                            Title = "Book 65"
                        },
                        new
                        {
                            Id = "354f07d6-112a-4f7e-ba82-cd8bc0cefddf",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1085),
                            Description = "<p>Book 69 is simply dummy text of the printing and typesetting industry. Book 69 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 69 has been the book. </p><p>Book 69's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-69",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1086),
                            Status = 1,
                            Title = "Book 69"
                        },
                        new
                        {
                            Id = "e8cff779-7531-41da-add2-635dac60d139",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1158),
                            Description = "<p>Book 73 is simply dummy text of the printing and typesetting industry. Book 73 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 73 has been the book. </p><p>Book 73's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-73",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1159),
                            Status = 1,
                            Title = "Book 73"
                        },
                        new
                        {
                            Id = "a3cfcdda-639b-4342-b8af-22e9c907ff83",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1200),
                            Description = "<p>Book 77 is simply dummy text of the printing and typesetting industry. Book 77 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 77 has been the book. </p><p>Book 77's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-77",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1201),
                            Status = 1,
                            Title = "Book 77"
                        },
                        new
                        {
                            Id = "7d45aa39-b7fe-408d-b606-2729cc45929b",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1278),
                            Description = "<p>Book 81 is simply dummy text of the printing and typesetting industry. Book 81 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 81 has been the book. </p><p>Book 81's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-81",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1280),
                            Status = 1,
                            Title = "Book 81"
                        },
                        new
                        {
                            Id = "a73606f5-d76a-46d8-91bb-9737dec3064c",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1348),
                            Description = "<p>Book 85 is simply dummy text of the printing and typesetting industry. Book 85 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 85 has been the book. </p><p>Book 85's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-85",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1350),
                            Status = 1,
                            Title = "Book 85"
                        },
                        new
                        {
                            Id = "fc9d65bd-7e00-4242-9bf8-39b83736a79f",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1425),
                            Description = "<p>Book 89 is simply dummy text of the printing and typesetting industry. Book 89 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 89 has been the book. </p><p>Book 89's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-89",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 8, 1, 6, 22, 36, 248, DateTimeKind.Local).AddTicks(1427),
                            Status = 1,
                            Title = "Book 89"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.BookImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");

                    b.HasData(
                        new
                        {
                            Id = "e09087cd-5ae5-4e27-aa71-044ad0a909c1",
                            BookId = "9bb6c949-1bea-48a6-94a0-f2c4b1614b81",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/book-1.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "c930f692-da87-45a9-af78-a69264cc857a",
                            BookId = "9bb6c949-1bea-48a6-94a0-f2c4b1614b81",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "a2ca6675-7902-485a-a8cc-7d864923596c",
                            BookId = "9bb6c949-1bea-48a6-94a0-f2c4b1614b81",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "fbfdbb80-4a46-4700-8ba9-bd9a89329eff",
                            BookId = "446d4499-bd54-46e1-b93f-45b7e38101e1",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/book-5.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "0222ed86-816f-4047-b204-7014f9918a38",
                            BookId = "446d4499-bd54-46e1-b93f-45b7e38101e1",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "032bdcc3-920f-41eb-9077-313c4a6737f6",
                            BookId = "446d4499-bd54-46e1-b93f-45b7e38101e1",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "a60a3014-7783-4c27-8f54-a5af4b198cde",
                            BookId = "60300f7c-2afd-4309-882e-0e821bfbfed0",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/book-9.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "7abd4691-627d-43c8-9eac-af302b8bc419",
                            BookId = "60300f7c-2afd-4309-882e-0e821bfbfed0",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "033c668d-7ad0-433e-8fe1-c9b01e83e337",
                            BookId = "60300f7c-2afd-4309-882e-0e821bfbfed0",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "1d1f2471-c903-4141-8d12-2c52edfeed4d",
                            BookId = "6fbc53ee-78f0-4f73-a7f7-ec42084e1a2c",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/book-13.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "854129eb-9e55-4557-b3ed-299deb2e4444",
                            BookId = "6fbc53ee-78f0-4f73-a7f7-ec42084e1a2c",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "b2c53df1-061b-4045-9864-9075bd00874f",
                            BookId = "6fbc53ee-78f0-4f73-a7f7-ec42084e1a2c",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "a0c7678f-433b-45f7-a666-9fd6ce842b46",
                            BookId = "8fc1ddfe-4880-4ff8-b265-0e6f57afc1c1",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/book-17.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "6da96542-660a-4f37-b0d6-d00cb1f87222",
                            BookId = "8fc1ddfe-4880-4ff8-b265-0e6f57afc1c1",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "63600634-83a1-4cc3-b0c3-07b144ca6d2c",
                            BookId = "8fc1ddfe-4880-4ff8-b265-0e6f57afc1c1",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "55d97c95-8a30-4892-bc5a-d699e11c71ae",
                            BookId = "c0750072-426c-44cd-92d7-39bd02c71cf0",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/book-21.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "ec1afb29-3592-4004-b08b-8e773ef0d272",
                            BookId = "c0750072-426c-44cd-92d7-39bd02c71cf0",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "c0dea46d-30ee-4eea-bf57-e873f68d54c1",
                            BookId = "c0750072-426c-44cd-92d7-39bd02c71cf0",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "89f3d676-c94d-47e7-a98b-91515821719a",
                            BookId = "d6981c48-11c1-41d6-be9e-cf2a60dda2c6",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/book-25.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "8bfec877-3583-4755-92b4-dbd75eef95bc",
                            BookId = "d6981c48-11c1-41d6-be9e-cf2a60dda2c6",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "a99537c3-e60d-40bb-a607-c8d0ef78c352",
                            BookId = "d6981c48-11c1-41d6-be9e-cf2a60dda2c6",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "670cdb48-b36d-4c56-b5c2-06b318c88983",
                            BookId = "80a14e57-b9a4-47e9-9144-627e5b1668ee",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/book-29.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "5cc375c6-d3d1-41de-8f00-b828033b4e5c",
                            BookId = "80a14e57-b9a4-47e9-9144-627e5b1668ee",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "5f4c60eb-fa81-4955-8276-dda97ce920d6",
                            BookId = "80a14e57-b9a4-47e9-9144-627e5b1668ee",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "21c826e6-74f2-4fba-a63d-f77ea5019c93",
                            BookId = "ff2d5ebc-7a8f-467b-a983-357f33693840",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/book-33.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "57c7421b-01b2-473b-ad47-fa85021252bf",
                            BookId = "ff2d5ebc-7a8f-467b-a983-357f33693840",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "aed86228-93d9-4f4d-873a-07107987c56c",
                            BookId = "ff2d5ebc-7a8f-467b-a983-357f33693840",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "f77d63d6-18ca-4775-bf92-2bb16e0703ed",
                            BookId = "749ca424-9791-4693-a85a-0e1c955ac5f9",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/book-37.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "035785df-9fa3-44e0-86c2-29f14c5f74bd",
                            BookId = "749ca424-9791-4693-a85a-0e1c955ac5f9",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "f4ac4031-3ab4-4598-9b2a-b1b3ada80b77",
                            BookId = "749ca424-9791-4693-a85a-0e1c955ac5f9",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "8ded87ff-5edd-42e9-b51c-80909df4ff65",
                            BookId = "8d8bea9a-7125-49ec-99e9-1596eb1058f8",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/book-41.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "e6bbb354-68dd-40f5-8e64-4ed74c552ed5",
                            BookId = "8d8bea9a-7125-49ec-99e9-1596eb1058f8",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "35b486d1-773e-4dd0-ae10-105b0e45d016",
                            BookId = "8d8bea9a-7125-49ec-99e9-1596eb1058f8",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "50f68694-d058-4007-9386-8faa82453a6f",
                            BookId = "a10023f7-a765-4782-bc89-4891c2bc90dd",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/book-45.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "6adcc4ae-4a8f-495f-aed0-3c1cd0cf1b9c",
                            BookId = "a10023f7-a765-4782-bc89-4891c2bc90dd",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "a50a0d2c-e867-4a61-8e26-b3ef796029af",
                            BookId = "a10023f7-a765-4782-bc89-4891c2bc90dd",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "d9bd02b1-96ca-44b6-b83b-5bbc2f99a019",
                            BookId = "376cebea-4428-4746-8376-2055cd19c285",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/book-49.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "40110ada-93ac-40c5-849a-8ec6c933478a",
                            BookId = "376cebea-4428-4746-8376-2055cd19c285",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "77ca25aa-07b7-49b8-958c-d5a4adc90b0a",
                            BookId = "376cebea-4428-4746-8376-2055cd19c285",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "58c74c5b-43c2-47d7-974a-5494ec8dede0",
                            BookId = "e5db32f1-4e3a-489e-b22f-c4b2c415949f",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/book-53.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "357626b4-93a1-4824-8292-d46d9defdf26",
                            BookId = "e5db32f1-4e3a-489e-b22f-c4b2c415949f",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "7dcb7a2d-acd4-4081-a703-d513d5b907ab",
                            BookId = "e5db32f1-4e3a-489e-b22f-c4b2c415949f",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "1fa5d7b7-d538-4fa3-af1f-1468ab08bea9",
                            BookId = "419ea699-6f65-4918-9aa6-183bf61f3ab2",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/book-57.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "5f53efd8-cc61-4d01-8a8d-558262dd0181",
                            BookId = "419ea699-6f65-4918-9aa6-183bf61f3ab2",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "aeefc476-c30f-4a22-b226-4d95ef64a470",
                            BookId = "419ea699-6f65-4918-9aa6-183bf61f3ab2",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "7142a848-6b6d-41e5-9f78-0ecd48e15d48",
                            BookId = "e2d9cf0c-baa4-464b-9071-17db23fc3557",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/book-61.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "7b2a1227-689c-4e4a-b9bd-8ed5beadefbe",
                            BookId = "e2d9cf0c-baa4-464b-9071-17db23fc3557",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "736efc68-fd67-44d2-b176-612db0fb5268",
                            BookId = "e2d9cf0c-baa4-464b-9071-17db23fc3557",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "efeed228-222a-4ac2-953d-efd32eb0d85f",
                            BookId = "139dc314-c48d-4713-86ad-b51f83daed0c",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/book-65.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "cda1a5b4-65b8-4e68-a596-79bbc5d5efd5",
                            BookId = "139dc314-c48d-4713-86ad-b51f83daed0c",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "99e9708a-f4dc-40b9-87f2-6424f0b1a0dd",
                            BookId = "139dc314-c48d-4713-86ad-b51f83daed0c",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "76bbd5b1-5608-4a20-b45a-845ee7cc7d01",
                            BookId = "354f07d6-112a-4f7e-ba82-cd8bc0cefddf",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/book-69.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "233f1155-f930-455f-9a6d-bbe812e37823",
                            BookId = "354f07d6-112a-4f7e-ba82-cd8bc0cefddf",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "047845d7-96cf-47d9-bf65-61080ff49db5",
                            BookId = "354f07d6-112a-4f7e-ba82-cd8bc0cefddf",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "d39bb4c8-d420-4676-a833-742630d75f1d",
                            BookId = "e8cff779-7531-41da-add2-635dac60d139",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/book-73.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "cf76b9f2-aa42-4cd7-9073-7b8cba48ad66",
                            BookId = "e8cff779-7531-41da-add2-635dac60d139",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "e4878983-1ae7-4a71-bc99-ed5fc553656f",
                            BookId = "e8cff779-7531-41da-add2-635dac60d139",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "2be05978-1ddf-4c16-80eb-15ebe83ea6a7",
                            BookId = "a3cfcdda-639b-4342-b8af-22e9c907ff83",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/book-77.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "df4f0cb0-e1a7-4736-9f6f-2e9cd4751d5a",
                            BookId = "a3cfcdda-639b-4342-b8af-22e9c907ff83",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "b3d431e4-2a45-487d-9495-68c6e77d417c",
                            BookId = "a3cfcdda-639b-4342-b8af-22e9c907ff83",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "68f4213d-e1d5-422f-a00f-634041b1c921",
                            BookId = "7d45aa39-b7fe-408d-b606-2729cc45929b",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/book-81.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "1b41130a-1422-4302-8c4b-d1a38334ce92",
                            BookId = "7d45aa39-b7fe-408d-b606-2729cc45929b",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "39737ecd-261b-44c7-bdbe-5ab7fc74bbe3",
                            BookId = "7d45aa39-b7fe-408d-b606-2729cc45929b",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "f2d0b8d5-2a87-4ad8-ade9-788d110e7cae",
                            BookId = "a73606f5-d76a-46d8-91bb-9737dec3064c",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/book-85.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "281faead-5f5a-44d5-a294-2c75029a2c21",
                            BookId = "a73606f5-d76a-46d8-91bb-9737dec3064c",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "0d8d8a32-c72e-4d57-9ae8-601223adb5f6",
                            BookId = "a73606f5-d76a-46d8-91bb-9737dec3064c",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "c53c65fe-b296-475f-8bad-62a2f781c6ad",
                            BookId = "fc9d65bd-7e00-4242-9bf8-39b83736a79f",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/book-89.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "db27a8ed-541c-4530-9ffc-48b6c5264d85",
                            BookId = "fc9d65bd-7e00-4242-9bf8-39b83736a79f",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "6fa3dabe-cc48-4150-baf9-91085dd0821e",
                            BookId = "fc9d65bd-7e00-4242-9bf8-39b83736a79f",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Discount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = "471e6bd8-a175-449a-9626-b4bbe17d2729",
                            Name = "Default",
                            Value = 0
                        },
                        new
                        {
                            Id = "ab4317bb-7b09-4c5d-a655-334a59b5a821",
                            Name = "Test",
                            Value = 10
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.OrderDetail", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("BookId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Book", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Discount", "Discount")
                        .WithMany("Books")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.BookImage", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany("Images")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Order", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Discount", "Discount")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountId");

                    b.HasOne("NetCoreBookStore.Data.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCoreBookStore.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");
                });
#pragma warning restore 612, 618
        }
    }
}
