// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreBookStore.Data.EF;

namespace NetCoreBookStore.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200731014610_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("f2964f74-1c5c-419a-8377-bcc8e9ea4dc2"),
                            RoleId = new Guid("f2964f74-1c5c-419a-8377-bcc8e9ea4dc2")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2964f74-1c5c-419a-8377-bcc8e9ea4dc2"),
                            ConcurrencyStamp = "83c5927e-3b61-45d8-88aa-34cf8c6420cc",
                            Description = "Admin role",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2964f74-1c5c-419a-8377-bcc8e9ea4dc2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "45fc088d-1ffc-4bd2-82d8-424cc9a51a6f",
                            Dob = new DateTime(2020, 7, 31, 8, 46, 10, 79, DateTimeKind.Local).AddTicks(3810),
                            Email = "app-admin@abc.xyz",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "app-admin@abc.xyz",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ3ChWtoD1embU+yb5IvYuX+v6xhYt6C1n6coLiiHbn0VZOi+jVsP6gduf7DPY65zQ==",
                            PhoneNumber = "0985123745",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("NameAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = "593e92f9-f0b7-4309-bed6-a3d809e29c30",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 58, DateTimeKind.Local).AddTicks(4678),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-1",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 60, DateTimeKind.Local).AddTicks(84),
                            Status = 1,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = "fa4795c0-aafe-4b8b-8551-edd7bb0e096a",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(2911),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-5",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(2961),
                            Status = 1,
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = "60721ecf-f9ca-4e37-a5c7-4be6e8091f33",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3448),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-9",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3454),
                            Status = 1,
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = "33ac3cfb-73ad-40f9-b190-a945941aa7a9",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3544),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-13",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3546),
                            Status = 1,
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = "80bf9afd-f4ca-4202-87b5-e33f5012b6b4",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3622),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-17",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3624),
                            Status = 1,
                            Title = "Book 17"
                        },
                        new
                        {
                            Id = "f6e045fc-348d-4187-a699-245dfe161576",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3691),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-21",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3693),
                            Status = 1,
                            Title = "Book 21"
                        },
                        new
                        {
                            Id = "f027c8df-4cd0-4a65-b736-33daea3bc19c",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3760),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-25",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3762),
                            Status = 1,
                            Title = "Book 25"
                        },
                        new
                        {
                            Id = "44f9cd80-aca5-4d2a-bb03-7e4d0e22729f",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3819),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-29",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3821),
                            Status = 1,
                            Title = "Book 29"
                        },
                        new
                        {
                            Id = "865fc585-8d8d-4732-aac9-af45a463c5fc",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3931),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-33",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3933),
                            Status = 1,
                            Title = "Book 33"
                        },
                        new
                        {
                            Id = "c707d27f-eb52-4120-bc61-f06ec1adee1b",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3996),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-37",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(3998),
                            Status = 1,
                            Title = "Book 37"
                        },
                        new
                        {
                            Id = "1eb02c94-5042-4313-93cd-76be9619dc44",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4057),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-41",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4059),
                            Status = 1,
                            Title = "Book 41"
                        },
                        new
                        {
                            Id = "55dcfb6f-c301-46c1-86c9-577ba97f544f",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4119),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-45",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4121),
                            Status = 1,
                            Title = "Book 45"
                        },
                        new
                        {
                            Id = "dc36b925-0830-4ecc-91f0-3f01383d5774",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4180),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-49",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4182),
                            Status = 1,
                            Title = "Book 49"
                        },
                        new
                        {
                            Id = "9934542f-77c6-4784-a06f-a6032fb675e9",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4280),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-53",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4282),
                            Status = 1,
                            Title = "Book 53"
                        },
                        new
                        {
                            Id = "2dae4027-3766-41b5-a7a8-5539271add43",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4347),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-57",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4349),
                            Status = 1,
                            Title = "Book 57"
                        },
                        new
                        {
                            Id = "ed828d55-9587-4ca5-98e7-8ca4070eac54",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4409),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-61",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4411),
                            Status = 1,
                            Title = "Book 61"
                        },
                        new
                        {
                            Id = "ebb5f6cc-af3d-4eec-bf18-0122427ca937",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4476),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-65",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4478),
                            Status = 1,
                            Title = "Book 65"
                        },
                        new
                        {
                            Id = "602594bb-c561-4261-a6ee-477818418c27",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4547),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-69",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4548),
                            Status = 1,
                            Title = "Book 69"
                        },
                        new
                        {
                            Id = "60726fc9-b641-4a7a-aea4-26288ffaddc3",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4616),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-73",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4618),
                            Status = 1,
                            Title = "Book 73"
                        },
                        new
                        {
                            Id = "ff6ff11a-00d0-4c7f-aab1-8db92fd12a15",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4683),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-77",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4685),
                            Status = 1,
                            Title = "Book 77"
                        },
                        new
                        {
                            Id = "76309a43-eace-4ce8-9597-9a9dfd954aef",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4794),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-81",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4797),
                            Status = 1,
                            Title = "Book 81"
                        },
                        new
                        {
                            Id = "f6fee8a9-4079-4279-87f0-020338d5539b",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4905),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-85",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4907),
                            Status = 1,
                            Title = "Book 85"
                        },
                        new
                        {
                            Id = "1a3b9099-e755-4bb1-a7d9-1a0c580e768f",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4977),
                            Description = "Seeded book",
                            Edition = 2020,
                            NameAlias = "book-89",
                            Price = 33000.0,
                            PublicationDate = new DateTime(2020, 7, 31, 8, 46, 10, 61, DateTimeKind.Local).AddTicks(4979),
                            Status = 1,
                            Title = "Book 89"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.BookImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");

                    b.HasData(
                        new
                        {
                            Id = "1bc7a5d3-cc54-4552-9151-006f65a9c481",
                            BookId = "593e92f9-f0b7-4309-bed6-a3d809e29c30",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/book-1.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "93358177-8fe5-4a78-b2e1-8568c567faab",
                            BookId = "593e92f9-f0b7-4309-bed6-a3d809e29c30",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "ace45618-db22-44be-bac3-90b650e4bcbd",
                            BookId = "593e92f9-f0b7-4309-bed6-a3d809e29c30",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "f604a9fe-c03a-44be-86b7-0a00fa7c5072",
                            BookId = "fa4795c0-aafe-4b8b-8551-edd7bb0e096a",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/book-5.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "4b6ec743-853e-4c16-b36f-feda66772062",
                            BookId = "fa4795c0-aafe-4b8b-8551-edd7bb0e096a",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "16210f40-5cc9-4b99-aeaf-1cdf55a3167d",
                            BookId = "fa4795c0-aafe-4b8b-8551-edd7bb0e096a",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "78b019ce-0841-4e16-a94e-a1c55e1c9422",
                            BookId = "60721ecf-f9ca-4e37-a5c7-4be6e8091f33",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/book-9.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "26dfb064-08bd-442d-84ca-6353e145539f",
                            BookId = "60721ecf-f9ca-4e37-a5c7-4be6e8091f33",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "e58103a6-3301-4f21-8997-1540bb834d87",
                            BookId = "60721ecf-f9ca-4e37-a5c7-4be6e8091f33",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "dccd6a5d-c18c-4cb8-a1e3-998d9d047bd1",
                            BookId = "33ac3cfb-73ad-40f9-b190-a945941aa7a9",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/book-13.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "00c1ca78-0353-4f8c-b0fc-1dfe451fcc6c",
                            BookId = "33ac3cfb-73ad-40f9-b190-a945941aa7a9",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "f298f15f-dba6-4a1e-8ba3-3eb792828af9",
                            BookId = "33ac3cfb-73ad-40f9-b190-a945941aa7a9",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "f1a593f7-3e9b-4fc4-9040-5c794582cc31",
                            BookId = "80bf9afd-f4ca-4202-87b5-e33f5012b6b4",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/book-17.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "6e6ae6bc-7429-456d-b25b-8578a99b7848",
                            BookId = "80bf9afd-f4ca-4202-87b5-e33f5012b6b4",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "764aee56-590a-444d-8246-440a812eb61a",
                            BookId = "80bf9afd-f4ca-4202-87b5-e33f5012b6b4",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "c4a6740e-3863-4fe4-baf1-415e999d9392",
                            BookId = "f6e045fc-348d-4187-a699-245dfe161576",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/book-21.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "dc6ed6b6-46fc-43d5-afd5-d56597f0cd72",
                            BookId = "f6e045fc-348d-4187-a699-245dfe161576",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "586b8fec-a0e9-4ac8-a023-8118234df120",
                            BookId = "f6e045fc-348d-4187-a699-245dfe161576",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "fa659114-f0be-4a03-9c59-17f5d3672ae9",
                            BookId = "f027c8df-4cd0-4a65-b736-33daea3bc19c",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/book-25.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "08b4e402-64b7-4f07-9f28-a5aaa04ee9ae",
                            BookId = "f027c8df-4cd0-4a65-b736-33daea3bc19c",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "1cf222fe-6c34-4ac1-b202-00c8a6849a49",
                            BookId = "f027c8df-4cd0-4a65-b736-33daea3bc19c",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "0cec6ff3-1bc9-4dd0-8e00-bebda6161601",
                            BookId = "44f9cd80-aca5-4d2a-bb03-7e4d0e22729f",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/book-29.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "48447695-67c6-4bee-b011-6b54f90598d5",
                            BookId = "44f9cd80-aca5-4d2a-bb03-7e4d0e22729f",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "00cb6749-7c47-481d-850d-96c650a3cd44",
                            BookId = "44f9cd80-aca5-4d2a-bb03-7e4d0e22729f",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "6210cf1d-e07e-4a9c-9cd9-81c5e2c46c91",
                            BookId = "865fc585-8d8d-4732-aac9-af45a463c5fc",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/book-33.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "48d06958-f4d7-4851-90f0-d1eface39531",
                            BookId = "865fc585-8d8d-4732-aac9-af45a463c5fc",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "2191bc20-8acc-4c34-88ef-6b9f0f7967cc",
                            BookId = "865fc585-8d8d-4732-aac9-af45a463c5fc",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "86a21389-d4b7-4618-98de-622cff27e19b",
                            BookId = "c707d27f-eb52-4120-bc61-f06ec1adee1b",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/book-37.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "241d073b-66d6-405e-8f1b-e3b0101eb12f",
                            BookId = "c707d27f-eb52-4120-bc61-f06ec1adee1b",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "16ba4778-389e-4be7-9655-853a2cd2caab",
                            BookId = "c707d27f-eb52-4120-bc61-f06ec1adee1b",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "6934662d-b56a-4130-b776-5af9b4dd5f64",
                            BookId = "1eb02c94-5042-4313-93cd-76be9619dc44",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/book-41.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "6e672e17-263a-4452-98dd-a83f1b7634de",
                            BookId = "1eb02c94-5042-4313-93cd-76be9619dc44",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "c40cb235-d81b-43af-8dff-9e6603734d62",
                            BookId = "1eb02c94-5042-4313-93cd-76be9619dc44",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "4cc150a9-7eb5-41e9-8e2a-d407f25663dc",
                            BookId = "55dcfb6f-c301-46c1-86c9-577ba97f544f",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/book-45.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "8538ce1f-30cd-4ff9-a972-2cc39b5f3c89",
                            BookId = "55dcfb6f-c301-46c1-86c9-577ba97f544f",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "f8c670fe-c0b0-4ae6-a284-0da6b111e6f6",
                            BookId = "55dcfb6f-c301-46c1-86c9-577ba97f544f",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "32eaf61d-5afd-4bca-8985-db0cd6964b97",
                            BookId = "dc36b925-0830-4ecc-91f0-3f01383d5774",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/book-49.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "2e34923d-4018-41ee-bbb5-c0b69134a327",
                            BookId = "dc36b925-0830-4ecc-91f0-3f01383d5774",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "86f706c8-7972-4bbf-8d03-6018b96d93a9",
                            BookId = "dc36b925-0830-4ecc-91f0-3f01383d5774",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "226d2d0c-c66c-4f8d-829b-12a3355bbc1e",
                            BookId = "9934542f-77c6-4784-a06f-a6032fb675e9",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/book-53.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "bb148705-4c43-400b-af61-99edb90c0ee2",
                            BookId = "9934542f-77c6-4784-a06f-a6032fb675e9",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "fd978078-542f-408c-9a07-d6405737eee9",
                            BookId = "9934542f-77c6-4784-a06f-a6032fb675e9",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "c93d05b5-01a9-4655-8e1b-a835a9522f64",
                            BookId = "2dae4027-3766-41b5-a7a8-5539271add43",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/book-57.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "120ee072-4598-429f-b138-28c7c8ad1e3a",
                            BookId = "2dae4027-3766-41b5-a7a8-5539271add43",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "bb1fb524-8ef5-41ea-838c-c1217f7cf933",
                            BookId = "2dae4027-3766-41b5-a7a8-5539271add43",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "0243fd70-141d-4e05-845b-ca10c3c60c30",
                            BookId = "ed828d55-9587-4ca5-98e7-8ca4070eac54",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/book-61.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "c01b8db0-977f-4db0-bda0-111849e773bf",
                            BookId = "ed828d55-9587-4ca5-98e7-8ca4070eac54",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "9f6b6ce2-bd1b-4afc-8bec-a725516acfe1",
                            BookId = "ed828d55-9587-4ca5-98e7-8ca4070eac54",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "ad652e0e-fbed-49a4-821e-56decf32c5f6",
                            BookId = "ebb5f6cc-af3d-4eec-bf18-0122427ca937",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/book-65.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "0fe57248-bb7a-47e5-96ab-2140a304ebe6",
                            BookId = "ebb5f6cc-af3d-4eec-bf18-0122427ca937",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "1ecdbcf0-21fc-4fc6-9077-8005a98684f0",
                            BookId = "ebb5f6cc-af3d-4eec-bf18-0122427ca937",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "a31ccd17-759b-43a7-9970-fab978374b75",
                            BookId = "602594bb-c561-4261-a6ee-477818418c27",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/book-69.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "240516ba-1bcc-4b57-b153-f7ff11123aad",
                            BookId = "602594bb-c561-4261-a6ee-477818418c27",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "a37483bc-35d1-4712-b652-d3744e9c222d",
                            BookId = "602594bb-c561-4261-a6ee-477818418c27",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "7605d0bd-9ee5-4080-9f6d-d2cb4630f545",
                            BookId = "60726fc9-b641-4a7a-aea4-26288ffaddc3",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/book-73.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "b93c73d2-5dc4-46ee-8163-b31e19dbe38b",
                            BookId = "60726fc9-b641-4a7a-aea4-26288ffaddc3",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "167fa017-b42a-46be-bf26-9b422f7ece47",
                            BookId = "60726fc9-b641-4a7a-aea4-26288ffaddc3",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "09842bd0-acad-4155-891a-d1f101a1d965",
                            BookId = "ff6ff11a-00d0-4c7f-aab1-8db92fd12a15",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/book-77.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "6f875d37-3806-42aa-8840-290ea3a751d8",
                            BookId = "ff6ff11a-00d0-4c7f-aab1-8db92fd12a15",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "94eb1ad2-8299-458d-b615-a090c8e8108e",
                            BookId = "ff6ff11a-00d0-4c7f-aab1-8db92fd12a15",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "bbe27580-2cca-40a6-a8fb-3e0e27b54de9",
                            BookId = "76309a43-eace-4ce8-9597-9a9dfd954aef",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/book-81.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "a5c15520-519e-469a-a2a7-711fa48eeb15",
                            BookId = "76309a43-eace-4ce8-9597-9a9dfd954aef",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "076fbc43-9c7a-485d-b871-cdceb9e9239a",
                            BookId = "76309a43-eace-4ce8-9597-9a9dfd954aef",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "95f61cf5-e106-45fb-9f7c-d11ce02170f1",
                            BookId = "f6fee8a9-4079-4279-87f0-020338d5539b",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/book-85.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "73f017e5-8d27-417b-8886-8766ded5694e",
                            BookId = "f6fee8a9-4079-4279-87f0-020338d5539b",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "8a2e9fe0-c630-4786-b6b2-74d78f9d9dfd",
                            BookId = "f6fee8a9-4079-4279-87f0-020338d5539b",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "3e897950-4056-4810-b385-07cc48f17a97",
                            BookId = "1a3b9099-e755-4bb1-a7d9-1a0c580e768f",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/book-89.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "0d42cb1e-5f10-4f1e-83ae-cf5e568173e4",
                            BookId = "1a3b9099-e755-4bb1-a7d9-1a0c580e768f",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "0f11e19e-ce2f-49af-907d-ad971affbb5b",
                            BookId = "1a3b9099-e755-4bb1-a7d9-1a0c580e768f",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Discount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = "08c3ff1c-d6e4-430a-b81b-1e98e26c734f",
                            Name = "Default",
                            Value = 0
                        },
                        new
                        {
                            Id = "426ebd3f-aab4-479c-a3a0-6dda41ba33c6",
                            Name = "Test",
                            Value = 10
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.OrderDetail", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Book", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Discount", "Discount")
                        .WithMany("Books")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.BookImage", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany("Images")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Order", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Discount", "Discount")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountId");

                    b.HasOne("NetCoreBookStore.Data.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCoreBookStore.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
