// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreBookStore.Data.EF;

namespace NetCoreBookStore.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b132c356-3cf7-4264-a049-73fb409b83f6"),
                            RoleId = new Guid("b132c356-3cf7-4264-a049-73fb409b83f6")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b132c356-3cf7-4264-a049-73fb409b83f6"),
                            ConcurrencyStamp = "2ae44942-3995-47a8-ac9f-e721a0930d8e",
                            Description = "Admin role",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b132c356-3cf7-4264-a049-73fb409b83f6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8d7d222-f539-476a-95fd-b6ab950a398b",
                            Dob = new DateTime(2020, 8, 1, 10, 19, 52, 904, DateTimeKind.Local).AddTicks(8864),
                            Email = "app-admin@abc.xyz",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "app-admin@abc.xyz",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEHG4M3QfM5UNqdnx4AX9KBKjM/mjYg2+POtuCwxPuGZAd+5aEXWHm3YCBCVDJNnMVA==",
                            PhoneNumber = "0985123745",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("NameAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = "15dde85c-1320-404e-9f73-5e8e93d09a01",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 891, DateTimeKind.Local).AddTicks(910),
                            Description = "<p>Book 1 is simply dummy text of the printing and typesetting industry. Book 1 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 1 has been the book. </p><p>Book 1's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-1",
                            Price = 44.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 892, DateTimeKind.Local).AddTicks(1258),
                            Status = 1,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = "897d3b35-2fdc-413b-a7d2-69a9f0d5ccda",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1018),
                            Description = "<p>Book 5 is simply dummy text of the printing and typesetting industry. Book 5 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 5 has been the book. </p><p>Book 5's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-5",
                            Price = 49.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1034),
                            Status = 1,
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = "41246deb-a426-405a-932c-e8584cebef4a",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1328),
                            Description = "<p>Book 9 is simply dummy text of the printing and typesetting industry. Book 9 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 9 has been the book. </p><p>Book 9's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-9",
                            Price = 37.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1331),
                            Status = 1,
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = "16a64741-1a60-4869-b82e-63d01bd6bca4",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1384),
                            Description = "<p>Book 13 is simply dummy text of the printing and typesetting industry. Book 13 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 13 has been the book. </p><p>Book 13's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-13",
                            Price = 44.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1386),
                            Status = 1,
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = "6e8f0d97-2e30-4e35-b502-924e32443a92",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1431),
                            Description = "<p>Book 17 is simply dummy text of the printing and typesetting industry. Book 17 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 17 has been the book. </p><p>Book 17's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-17",
                            Price = 51.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1432),
                            Status = 1,
                            Title = "Book 17"
                        },
                        new
                        {
                            Id = "fb10958e-e137-49d5-83ca-fceb33d618aa",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1475),
                            Description = "<p>Book 21 is simply dummy text of the printing and typesetting industry. Book 21 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 21 has been the book. </p><p>Book 21's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-21",
                            Price = 44.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1476),
                            Status = 1,
                            Title = "Book 21"
                        },
                        new
                        {
                            Id = "b3af735c-3d10-4c6e-a384-0727c0e42d81",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1548),
                            Description = "<p>Book 25 is simply dummy text of the printing and typesetting industry. Book 25 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 25 has been the book. </p><p>Book 25's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-25",
                            Price = 43.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1549),
                            Status = 1,
                            Title = "Book 25"
                        },
                        new
                        {
                            Id = "d8e689f3-6d5e-4e3e-aae9-96c75242bf79",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1592),
                            Description = "<p>Book 29 is simply dummy text of the printing and typesetting industry. Book 29 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 29 has been the book. </p><p>Book 29's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-29",
                            Price = 52.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1593),
                            Status = 1,
                            Title = "Book 29"
                        },
                        new
                        {
                            Id = "23a03cb1-bbe0-439e-b3ad-8a32b9629b90",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1635),
                            Description = "<p>Book 33 is simply dummy text of the printing and typesetting industry. Book 33 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 33 has been the book. </p><p>Book 33's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-33",
                            Price = 45.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1636),
                            Status = 1,
                            Title = "Book 33"
                        },
                        new
                        {
                            Id = "fc23afbf-a380-4fc4-b7f2-fdb0838ff8cb",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1678),
                            Description = "<p>Book 37 is simply dummy text of the printing and typesetting industry. Book 37 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 37 has been the book. </p><p>Book 37's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-37",
                            Price = 47.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1679),
                            Status = 1,
                            Title = "Book 37"
                        },
                        new
                        {
                            Id = "1d0d3674-0ef1-439c-b056-a9aa16323218",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1749),
                            Description = "<p>Book 41 is simply dummy text of the printing and typesetting industry. Book 41 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 41 has been the book. </p><p>Book 41's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-41",
                            Price = 56.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1751),
                            Status = 1,
                            Title = "Book 41"
                        },
                        new
                        {
                            Id = "73e4f44b-ac8c-4463-86e0-9bb1bf4e0f6e",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1794),
                            Description = "<p>Book 45 is simply dummy text of the printing and typesetting industry. Book 45 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 45 has been the book. </p><p>Book 45's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-45",
                            Price = 54.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1795),
                            Status = 1,
                            Title = "Book 45"
                        },
                        new
                        {
                            Id = "91ca8d0c-c0bc-431a-ace8-0931cbac0586",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1836),
                            Description = "<p>Book 49 is simply dummy text of the printing and typesetting industry. Book 49 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 49 has been the book. </p><p>Book 49's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-49",
                            Price = 41.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1837),
                            Status = 1,
                            Title = "Book 49"
                        },
                        new
                        {
                            Id = "44e65d3f-7b59-4c75-999b-ff090b00af0d",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1875),
                            Description = "<p>Book 53 is simply dummy text of the printing and typesetting industry. Book 53 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 53 has been the book. </p><p>Book 53's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-53",
                            Price = 51.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1876),
                            Status = 1,
                            Title = "Book 53"
                        },
                        new
                        {
                            Id = "db27d1c5-aefb-4b36-9ac9-6d2d44ffa694",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1943),
                            Description = "<p>Book 57 is simply dummy text of the printing and typesetting industry. Book 57 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 57 has been the book. </p><p>Book 57's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-57",
                            Price = 51.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1944),
                            Status = 1,
                            Title = "Book 57"
                        },
                        new
                        {
                            Id = "da470b9d-ed8a-4833-b42b-e7550f4d0370",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1985),
                            Description = "<p>Book 61 is simply dummy text of the printing and typesetting industry. Book 61 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 61 has been the book. </p><p>Book 61's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-61",
                            Price = 53.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(1986),
                            Status = 1,
                            Title = "Book 61"
                        },
                        new
                        {
                            Id = "78e16958-4aef-4420-b1bf-9be01ae5ae1c",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2028),
                            Description = "<p>Book 65 is simply dummy text of the printing and typesetting industry. Book 65 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 65 has been the book. </p><p>Book 65's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-65",
                            Price = 56.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2030),
                            Status = 1,
                            Title = "Book 65"
                        },
                        new
                        {
                            Id = "421cc82f-ab9e-4279-8b66-a584dd7c5a17",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2068),
                            Description = "<p>Book 69 is simply dummy text of the printing and typesetting industry. Book 69 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 69 has been the book. </p><p>Book 69's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-69",
                            Price = 53.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2070),
                            Status = 1,
                            Title = "Book 69"
                        },
                        new
                        {
                            Id = "74b4e779-4568-4ce7-89cd-910d538de1de",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2110),
                            Description = "<p>Book 73 is simply dummy text of the printing and typesetting industry. Book 73 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 73 has been the book. </p><p>Book 73's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-73",
                            Price = 56.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2112),
                            Status = 1,
                            Title = "Book 73"
                        },
                        new
                        {
                            Id = "a52af41f-d5aa-49f2-8a17-588e55cb63d2",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2207),
                            Description = "<p>Book 77 is simply dummy text of the printing and typesetting industry. Book 77 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 77 has been the book. </p><p>Book 77's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-77",
                            Price = 56.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2208),
                            Status = 1,
                            Title = "Book 77"
                        },
                        new
                        {
                            Id = "4d822ec7-4778-42eb-a57a-7744bce1c4c2",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2265),
                            Description = "<p>Book 81 is simply dummy text of the printing and typesetting industry. Book 81 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 81 has been the book. </p><p>Book 81's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-81",
                            Price = 56.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2266),
                            Status = 1,
                            Title = "Book 81"
                        },
                        new
                        {
                            Id = "dc2726ed-54fb-4325-809e-0e9337dbedda",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2308),
                            Description = "<p>Book 85 is simply dummy text of the printing and typesetting industry. Book 85 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 85 has been the book. </p><p>Book 85's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-85",
                            Price = 52.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2309),
                            Status = 1,
                            Title = "Book 85"
                        },
                        new
                        {
                            Id = "665c42b0-cab8-4a6d-aa40-ee129e5648d7",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2408),
                            Description = "<p>Book 89 is simply dummy text of the printing and typesetting industry. Book 89 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 89 has been the book. </p><p>Book 89's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-89",
                            Price = 51.0,
                            PublicationDate = new DateTime(2020, 8, 1, 10, 19, 52, 893, DateTimeKind.Local).AddTicks(2410),
                            Status = 1,
                            Title = "Book 89"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.BookImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");

                    b.HasData(
                        new
                        {
                            Id = "d52c381e-71d4-4b92-9ae8-ad26ac9cb6a7",
                            BookId = "15dde85c-1320-404e-9f73-5e8e93d09a01",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/book-1.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "dff0b5cb-fcca-4826-9ad8-532efdff9ee2",
                            BookId = "15dde85c-1320-404e-9f73-5e8e93d09a01",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "00c74f77-6f6e-43d2-b25d-00e8ddc90ba7",
                            BookId = "15dde85c-1320-404e-9f73-5e8e93d09a01",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "b1953e14-141f-4044-aa84-83b3deb536c5",
                            BookId = "897d3b35-2fdc-413b-a7d2-69a9f0d5ccda",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/book-5.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "11161700-4bff-4756-878d-40f9d89cb14c",
                            BookId = "897d3b35-2fdc-413b-a7d2-69a9f0d5ccda",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "fca98d0b-5005-42c3-968a-4d3d79c847a3",
                            BookId = "897d3b35-2fdc-413b-a7d2-69a9f0d5ccda",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "972d5f5d-9c03-4eb6-bf28-31c291a7c129",
                            BookId = "41246deb-a426-405a-932c-e8584cebef4a",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/book-9.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "ac8fa01f-d900-4866-b892-8ab35b3f6f51",
                            BookId = "41246deb-a426-405a-932c-e8584cebef4a",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "75533d75-9275-4e4a-afc0-2ffc6116e5b2",
                            BookId = "41246deb-a426-405a-932c-e8584cebef4a",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "c6f52b55-7f28-43b9-bc78-8b69174affe5",
                            BookId = "16a64741-1a60-4869-b82e-63d01bd6bca4",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/book-13.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "df44d4a5-902a-4caf-a921-fdee82d266d5",
                            BookId = "16a64741-1a60-4869-b82e-63d01bd6bca4",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "a8fe4853-2cf4-407f-9f80-88a8c48e2427",
                            BookId = "16a64741-1a60-4869-b82e-63d01bd6bca4",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "b00e733b-1d8f-49f5-ad52-ae7ed2eaaa3a",
                            BookId = "6e8f0d97-2e30-4e35-b502-924e32443a92",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/book-17.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "cd67f7db-054f-4177-9e11-40e5bc227724",
                            BookId = "6e8f0d97-2e30-4e35-b502-924e32443a92",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "e59ee496-98cc-460d-9aef-f0c6be975197",
                            BookId = "6e8f0d97-2e30-4e35-b502-924e32443a92",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "dd021c84-922e-4471-98f1-1ce34114bbe3",
                            BookId = "fb10958e-e137-49d5-83ca-fceb33d618aa",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/book-21.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "c6159448-d249-4e21-b53c-47ad59f0da0f",
                            BookId = "fb10958e-e137-49d5-83ca-fceb33d618aa",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "c509b1e5-4bb6-4fad-8d05-cd2c0dd325a5",
                            BookId = "fb10958e-e137-49d5-83ca-fceb33d618aa",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "8f47e025-29d2-480d-bf38-3dbf3dae535f",
                            BookId = "b3af735c-3d10-4c6e-a384-0727c0e42d81",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/book-25.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "63f7f695-0249-45d8-a066-f739196ed775",
                            BookId = "b3af735c-3d10-4c6e-a384-0727c0e42d81",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "aee8399b-800c-437d-bd06-508f58139681",
                            BookId = "b3af735c-3d10-4c6e-a384-0727c0e42d81",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "e274af1a-f30f-4259-884a-ef8cf223caf4",
                            BookId = "d8e689f3-6d5e-4e3e-aae9-96c75242bf79",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/book-29.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "6b342709-f739-4e1a-98f5-87d23e05d55f",
                            BookId = "d8e689f3-6d5e-4e3e-aae9-96c75242bf79",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "0a51877d-b9d1-4385-9bf2-6490e278e3bb",
                            BookId = "d8e689f3-6d5e-4e3e-aae9-96c75242bf79",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "82c5531f-165e-4d96-a63d-46a7605a5e1f",
                            BookId = "23a03cb1-bbe0-439e-b3ad-8a32b9629b90",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/book-33.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "b5929100-82a3-4b87-93b3-f69a542a91c3",
                            BookId = "23a03cb1-bbe0-439e-b3ad-8a32b9629b90",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "17fc1915-0746-44a9-8424-975c27a62212",
                            BookId = "23a03cb1-bbe0-439e-b3ad-8a32b9629b90",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "5452f8a3-95ad-4f5d-ac33-b2b5253676e9",
                            BookId = "fc23afbf-a380-4fc4-b7f2-fdb0838ff8cb",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/book-37.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "3faf57fa-2c53-46cd-a72e-999b58c0a2cf",
                            BookId = "fc23afbf-a380-4fc4-b7f2-fdb0838ff8cb",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "9e7566ee-bc32-4f40-9e09-c65c1a80bb59",
                            BookId = "fc23afbf-a380-4fc4-b7f2-fdb0838ff8cb",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "cc7818bc-2a48-4c96-9645-d5410031dbda",
                            BookId = "1d0d3674-0ef1-439c-b056-a9aa16323218",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/book-41.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "acc3a647-de93-4dc6-a9fb-34959ced098f",
                            BookId = "1d0d3674-0ef1-439c-b056-a9aa16323218",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "e3787bd2-9a92-4153-a235-18c279e20e14",
                            BookId = "1d0d3674-0ef1-439c-b056-a9aa16323218",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "872f6653-cdca-449f-84ee-bb5aa2860a66",
                            BookId = "73e4f44b-ac8c-4463-86e0-9bb1bf4e0f6e",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/book-45.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "e95a4538-3120-49c0-95cc-977d57f914fd",
                            BookId = "73e4f44b-ac8c-4463-86e0-9bb1bf4e0f6e",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "a5da2497-748e-4665-9273-18caea6ed452",
                            BookId = "73e4f44b-ac8c-4463-86e0-9bb1bf4e0f6e",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "bb33a74d-61e5-499d-acbe-db3c11eb6500",
                            BookId = "91ca8d0c-c0bc-431a-ace8-0931cbac0586",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/book-49.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "b54fb8cd-62d8-469b-ba7e-7bcedd42fb75",
                            BookId = "91ca8d0c-c0bc-431a-ace8-0931cbac0586",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "db8e5a51-f422-4138-812d-63a028403fe8",
                            BookId = "91ca8d0c-c0bc-431a-ace8-0931cbac0586",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "a9aeb948-8123-4d22-afd3-e529f571f918",
                            BookId = "44e65d3f-7b59-4c75-999b-ff090b00af0d",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/book-53.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "7f6d5e46-50f1-4fbf-ac45-d80374f6dc96",
                            BookId = "44e65d3f-7b59-4c75-999b-ff090b00af0d",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "5a8393de-c616-4256-91bd-5f35145c0365",
                            BookId = "44e65d3f-7b59-4c75-999b-ff090b00af0d",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "7f708594-0e1e-4f5a-b440-8b7cb3fddd90",
                            BookId = "db27d1c5-aefb-4b36-9ac9-6d2d44ffa694",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/book-57.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "c53de695-7afd-4776-931e-19567d283039",
                            BookId = "db27d1c5-aefb-4b36-9ac9-6d2d44ffa694",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "4cce2cb6-9b22-47d3-a1ee-b29306dd01e7",
                            BookId = "db27d1c5-aefb-4b36-9ac9-6d2d44ffa694",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "eab44d13-77b8-42b8-a42a-090cbfcf1e67",
                            BookId = "da470b9d-ed8a-4833-b42b-e7550f4d0370",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/book-61.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "4a346761-fb16-4a15-a12d-87ee43e209d0",
                            BookId = "da470b9d-ed8a-4833-b42b-e7550f4d0370",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "a57c2001-89fc-46d3-bb41-789c1e2fb8b3",
                            BookId = "da470b9d-ed8a-4833-b42b-e7550f4d0370",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "a0f6cebc-e78d-499a-bef9-4872333166d6",
                            BookId = "78e16958-4aef-4420-b1bf-9be01ae5ae1c",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/book-65.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "33d45fa8-9028-4efd-9727-4ebd950e327f",
                            BookId = "78e16958-4aef-4420-b1bf-9be01ae5ae1c",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "906bfbee-d0ec-49cd-9797-bd582c03331a",
                            BookId = "78e16958-4aef-4420-b1bf-9be01ae5ae1c",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "2c6c6696-4c3e-407b-8c06-d249520a90e4",
                            BookId = "421cc82f-ab9e-4279-8b66-a584dd7c5a17",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/book-69.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "0ee1fda6-a9c7-42b8-975f-39071a2aa559",
                            BookId = "421cc82f-ab9e-4279-8b66-a584dd7c5a17",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "ec5c3a91-1e66-41bf-a94a-af4f56e96d3a",
                            BookId = "421cc82f-ab9e-4279-8b66-a584dd7c5a17",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "5018922c-063f-42cb-839a-fe9d5313e0df",
                            BookId = "74b4e779-4568-4ce7-89cd-910d538de1de",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/book-73.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "c5231ef6-f271-4d05-a126-d23fadaf9a45",
                            BookId = "74b4e779-4568-4ce7-89cd-910d538de1de",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "93d69ae5-9943-45ca-8ce9-453c5d1d3da3",
                            BookId = "74b4e779-4568-4ce7-89cd-910d538de1de",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "df5a124d-bb31-45d8-929b-108852884a49",
                            BookId = "a52af41f-d5aa-49f2-8a17-588e55cb63d2",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/book-77.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "9429a39f-a09f-4553-9b06-ead931e997af",
                            BookId = "a52af41f-d5aa-49f2-8a17-588e55cb63d2",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "af26c9d6-e259-4bc4-9215-410be0970fa4",
                            BookId = "a52af41f-d5aa-49f2-8a17-588e55cb63d2",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "c2cd9f23-0dc6-4e72-ac58-c9c1cfafccb8",
                            BookId = "4d822ec7-4778-42eb-a57a-7744bce1c4c2",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/book-81.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "5b85c5f9-845e-43e6-abd7-9216e7febdeb",
                            BookId = "4d822ec7-4778-42eb-a57a-7744bce1c4c2",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "af9a8569-8c25-4a83-8ec2-0d997293144e",
                            BookId = "4d822ec7-4778-42eb-a57a-7744bce1c4c2",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "b5dd78b6-3459-40fd-bbc7-f5e33902832c",
                            BookId = "dc2726ed-54fb-4325-809e-0e9337dbedda",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/book-85.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "9c9391f7-4fc2-4d19-b5e7-4c6c9b4aba94",
                            BookId = "dc2726ed-54fb-4325-809e-0e9337dbedda",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "8d1fb515-908e-4b22-b91f-dffa213133aa",
                            BookId = "dc2726ed-54fb-4325-809e-0e9337dbedda",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "2b428d84-353c-470b-9250-5372fdafb169",
                            BookId = "665c42b0-cab8-4a6d-aa40-ee129e5648d7",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/book-89.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "680a9610-7648-4f28-88cb-ef33f1a5099d",
                            BookId = "665c42b0-cab8-4a6d-aa40-ee129e5648d7",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "5bf4eb66-3fff-4a21-b312-d29bf8619498",
                            BookId = "665c42b0-cab8-4a6d-aa40-ee129e5648d7",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Discount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = "9e30eeeb-39e2-4be6-a2ca-9525484f8f58",
                            Name = "Default",
                            Value = 0
                        },
                        new
                        {
                            Id = "24c5fc91-c7f9-4241-aa59-430defe3af81",
                            Name = "Test",
                            Value = 10
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.OrderDetail", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("BookId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Book", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Discount", "Discount")
                        .WithMany("Books")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.BookImage", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany("Images")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Order", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Discount", "Discount")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountId");

                    b.HasOne("NetCoreBookStore.Data.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCoreBookStore.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");
                });
#pragma warning restore 612, 618
        }
    }
}
