// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreBookStore.Core.EF;

namespace NetCoreBookStore.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d57d5a15-38a7-41f1-b834-9ac9d25a6d1a"),
                            RoleId = new Guid("d57d5a15-38a7-41f1-b834-9ac9d25a6d1a")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d57d5a15-38a7-41f1-b834-9ac9d25a6d1a"),
                            ConcurrencyStamp = "2fbc4f9f-6c47-4d64-be9a-273c4e12aa5a",
                            Description = "Admin role",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d57d5a15-38a7-41f1-b834-9ac9d25a6d1a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6ac18923-972a-4fcb-a84b-55882c3fd936",
                            Dob = new DateTime(2020, 8, 4, 9, 32, 55, 856, DateTimeKind.Local).AddTicks(285),
                            Email = "app-admin@abc.xyz",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "app-admin@abc.xyz",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEMTfFbwk+ZrXh2kE4PHV9o0nyMbBLW7nLkFNwS42lHktLg5VmFeTpNuKfgnhG3yNag==",
                            PhoneNumber = "0985123745",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("NameAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = "ffd4d9fa-7e93-4f6e-8750-f0a184ecf408",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 843, DateTimeKind.Local).AddTicks(6361),
                            Description = "<p>Book 1 is simply dummy text of the printing and typesetting industry. Book 1 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 1 has been the book. </p><p>Book 1's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-1",
                            Price = 42.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 844, DateTimeKind.Local).AddTicks(4904),
                            Status = 1,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = "717e475a-5e9f-4f2d-b9c6-55e3f595d75c",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(3834),
                            Description = "<p>Book 5 is simply dummy text of the printing and typesetting industry. Book 5 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 5 has been the book. </p><p>Book 5's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-5",
                            Price = 44.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(3869),
                            Status = 1,
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = "3426af09-27ed-4e79-9788-50b9c7b7bb0b",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4066),
                            Description = "<p>Book 9 is simply dummy text of the printing and typesetting industry. Book 9 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 9 has been the book. </p><p>Book 9's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-9",
                            Price = 39.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4069),
                            Status = 1,
                            Title = "Book 9"
                        },
                        new
                        {
                            Id = "09407254-23e9-4b6a-ad28-d6fa7c981d65",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4117),
                            Description = "<p>Book 13 is simply dummy text of the printing and typesetting industry. Book 13 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 13 has been the book. </p><p>Book 13's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-13",
                            Price = 39.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4119),
                            Status = 1,
                            Title = "Book 13"
                        },
                        new
                        {
                            Id = "e2c5009e-e913-471e-b0db-0e405408235e",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4209),
                            Description = "<p>Book 17 is simply dummy text of the printing and typesetting industry. Book 17 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 17 has been the book. </p><p>Book 17's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-17",
                            Price = 45.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4210),
                            Status = 1,
                            Title = "Book 17"
                        },
                        new
                        {
                            Id = "064bcbf9-f4e5-4d58-b2d6-6a4ac90c1abc",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4251),
                            Description = "<p>Book 21 is simply dummy text of the printing and typesetting industry. Book 21 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 21 has been the book. </p><p>Book 21's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-21",
                            Price = 50.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4253),
                            Status = 1,
                            Title = "Book 21"
                        },
                        new
                        {
                            Id = "3f6a29a0-526c-4caf-bad1-33a16c9e855e",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4296),
                            Description = "<p>Book 25 is simply dummy text of the printing and typesetting industry. Book 25 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 25 has been the book. </p><p>Book 25's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-25",
                            Price = 45.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4297),
                            Status = 1,
                            Title = "Book 25"
                        },
                        new
                        {
                            Id = "5f4b30be-e72d-41df-9499-de6d8643a6c8",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4337),
                            Description = "<p>Book 29 is simply dummy text of the printing and typesetting industry. Book 29 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 29 has been the book. </p><p>Book 29's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-29",
                            Price = 48.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4339),
                            Status = 1,
                            Title = "Book 29"
                        },
                        new
                        {
                            Id = "aa0cd836-05a5-4258-bcba-3726828b4a3e",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4413),
                            Description = "<p>Book 33 is simply dummy text of the printing and typesetting industry. Book 33 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 33 has been the book. </p><p>Book 33's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-33",
                            Price = 56.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4414),
                            Status = 1,
                            Title = "Book 33"
                        },
                        new
                        {
                            Id = "0218d7f0-e96a-453c-a817-b23c0c69de06",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4454),
                            Description = "<p>Book 37 is simply dummy text of the printing and typesetting industry. Book 37 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 37 has been the book. </p><p>Book 37's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-37",
                            Price = 49.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4456),
                            Status = 1,
                            Title = "Book 37"
                        },
                        new
                        {
                            Id = "cac93b25-95b7-4f1f-8544-df67b563220e",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4496),
                            Description = "<p>Book 41 is simply dummy text of the printing and typesetting industry. Book 41 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 41 has been the book. </p><p>Book 41's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-41",
                            Price = 45.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4498),
                            Status = 1,
                            Title = "Book 41"
                        },
                        new
                        {
                            Id = "73fd7b5f-5725-4998-91cf-48a7dc9fe7b7",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4538),
                            Description = "<p>Book 45 is simply dummy text of the printing and typesetting industry. Book 45 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 45 has been the book. </p><p>Book 45's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-45",
                            Price = 41.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4539),
                            Status = 1,
                            Title = "Book 45"
                        },
                        new
                        {
                            Id = "a2cb72af-b919-4489-939f-813aab6b997d",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4608),
                            Description = "<p>Book 49 is simply dummy text of the printing and typesetting industry. Book 49 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 49 has been the book. </p><p>Book 49's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-49",
                            Price = 41.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4609),
                            Status = 1,
                            Title = "Book 49"
                        },
                        new
                        {
                            Id = "abb2e9e0-18ba-49cd-b914-a6fb2527e923",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4648),
                            Description = "<p>Book 53 is simply dummy text of the printing and typesetting industry. Book 53 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 53 has been the book. </p><p>Book 53's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-53",
                            Price = 39.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4650),
                            Status = 1,
                            Title = "Book 53"
                        },
                        new
                        {
                            Id = "03c1b820-6a10-4581-9225-b34670b457e6",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4690),
                            Description = "<p>Book 57 is simply dummy text of the printing and typesetting industry. Book 57 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 57 has been the book. </p><p>Book 57's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-57",
                            Price = 46.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4691),
                            Status = 1,
                            Title = "Book 57"
                        },
                        new
                        {
                            Id = "c29c34e8-43ef-4ca4-8df3-39329d3fd6ae",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4729),
                            Description = "<p>Book 61 is simply dummy text of the printing and typesetting industry. Book 61 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 61 has been the book. </p><p>Book 61's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-61",
                            Price = 47.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4731),
                            Status = 1,
                            Title = "Book 61"
                        },
                        new
                        {
                            Id = "279353e2-537e-4270-93e8-9e7dbd3cac01",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4832),
                            Description = "<p>Book 65 is simply dummy text of the printing and typesetting industry. Book 65 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 65 has been the book. </p><p>Book 65's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-65",
                            Price = 47.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4833),
                            Status = 1,
                            Title = "Book 65"
                        },
                        new
                        {
                            Id = "69c7a1f8-528d-473f-a17f-f77c52ee5599",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4874),
                            Description = "<p>Book 69 is simply dummy text of the printing and typesetting industry. Book 69 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 69 has been the book. </p><p>Book 69's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-69",
                            Price = 52.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4875),
                            Status = 1,
                            Title = "Book 69"
                        },
                        new
                        {
                            Id = "7756e85e-2db5-4873-aff1-a0219598f7da",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4916),
                            Description = "<p>Book 73 is simply dummy text of the printing and typesetting industry. Book 73 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 73 has been the book. </p><p>Book 73's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-73",
                            Price = 49.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4917),
                            Status = 1,
                            Title = "Book 73"
                        },
                        new
                        {
                            Id = "7c59ec68-05fd-401d-be98-d32de44f8060",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4954),
                            Description = "<p>Book 77 is simply dummy text of the printing and typesetting industry. Book 77 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 77 has been the book. </p><p>Book 77's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-77",
                            Price = 39.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(4956),
                            Status = 1,
                            Title = "Book 77"
                        },
                        new
                        {
                            Id = "5b31c3e2-7d50-4da1-9bbc-973ed735b814",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(5045),
                            Description = "<p>Book 81 is simply dummy text of the printing and typesetting industry. Book 81 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 81 has been the book. </p><p>Book 81's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-81",
                            Price = 49.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(5046),
                            Status = 1,
                            Title = "Book 81"
                        },
                        new
                        {
                            Id = "c1b3a3a8-5cfd-4d58-bb65-fa046de6ba8d",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(5089),
                            Description = "<p>Book 85 is simply dummy text of the printing and typesetting industry. Book 85 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 85 has been the book. </p><p>Book 85's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-85",
                            Price = 48.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(5090),
                            Status = 1,
                            Title = "Book 85"
                        },
                        new
                        {
                            Id = "366edef8-a08b-474f-9d8e-0136b409d0c6",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(5132),
                            Description = "<p>Book 89 is simply dummy text of the printing and typesetting industry. Book 89 has been the industry's printer took a galley of type and Scrambled it to make a type and typesetting industry. Book 89 has been the book. </p><p>Book 89's Description here  </p>",
                            Edition = 2020,
                            NameAlias = "book-89",
                            Price = 46.0,
                            PublicationDate = new DateTime(2020, 8, 4, 9, 32, 55, 845, DateTimeKind.Local).AddTicks(5134),
                            Status = 1,
                            Title = "Book 89"
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.BookImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookImages");

                    b.HasData(
                        new
                        {
                            Id = "8ef2787b-68ee-4435-97e0-d2edf9b88141",
                            BookId = "ffd4d9fa-7e93-4f6e-8750-f0a184ecf408",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/book-1.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "4726229c-c246-4f64-9825-fcc710363562",
                            BookId = "ffd4d9fa-7e93-4f6e-8750-f0a184ecf408",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "fbd15345-4dc5-41a0-a37e-5eec74c956f8",
                            BookId = "ffd4d9fa-7e93-4f6e-8750-f0a184ecf408",
                            Description = "Book 1",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "886440b6-aff7-4bfd-b72e-cc301a2a7ecb",
                            BookId = "717e475a-5e9f-4f2d-b9c6-55e3f595d75c",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/book-5.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "aeb8abbe-08b7-4294-9d18-ef5eab36a045",
                            BookId = "717e475a-5e9f-4f2d-b9c6-55e3f595d75c",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "0ece1810-2850-4ded-ba9c-bd838def4c06",
                            BookId = "717e475a-5e9f-4f2d-b9c6-55e3f595d75c",
                            Description = "Book 5",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "4774f800-20ed-4591-9bdc-a799c4f29373",
                            BookId = "3426af09-27ed-4e79-9788-50b9c7b7bb0b",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/book-9.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "785f3ccc-c245-48e0-b52a-5937bba95e3a",
                            BookId = "3426af09-27ed-4e79-9788-50b9c7b7bb0b",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "95eaf031-ea47-43be-9c8b-f06159175fed",
                            BookId = "3426af09-27ed-4e79-9788-50b9c7b7bb0b",
                            Description = "Book 9",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "c733d15f-604b-494b-9be1-eeabac517d65",
                            BookId = "09407254-23e9-4b6a-ad28-d6fa7c981d65",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/book-13.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "8b37740a-93e7-4a31-9d37-2ceeed4af370",
                            BookId = "09407254-23e9-4b6a-ad28-d6fa7c981d65",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "383d56b7-3631-47b1-a8ec-9172098146b2",
                            BookId = "09407254-23e9-4b6a-ad28-d6fa7c981d65",
                            Description = "Book 13",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "eab4130d-0854-4c4d-a944-5f3fe834dd7e",
                            BookId = "e2c5009e-e913-471e-b0db-0e405408235e",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/book-17.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "e5eeeb86-63e8-4e53-99ca-e99424a4e847",
                            BookId = "e2c5009e-e913-471e-b0db-0e405408235e",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "e9341875-6a09-4eb2-a483-b336b6762c5f",
                            BookId = "e2c5009e-e913-471e-b0db-0e405408235e",
                            Description = "Book 17",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "a8b4d2d7-fafe-47cc-8e75-83e9304be7bb",
                            BookId = "064bcbf9-f4e5-4d58-b2d6-6a4ac90c1abc",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/book-21.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "7652c35f-e440-4717-9485-d08116b50f7d",
                            BookId = "064bcbf9-f4e5-4d58-b2d6-6a4ac90c1abc",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "d12aa015-318a-4ad8-949a-f3e5964f6847",
                            BookId = "064bcbf9-f4e5-4d58-b2d6-6a4ac90c1abc",
                            Description = "Book 21",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "4a5cf3f7-117c-45bf-a8e7-ed611eaca215",
                            BookId = "3f6a29a0-526c-4caf-bad1-33a16c9e855e",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/book-25.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "876608dd-ca73-41b0-840a-1b9c35769e27",
                            BookId = "3f6a29a0-526c-4caf-bad1-33a16c9e855e",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "0a934eba-a4bd-4fea-a57a-57baebbb63d2",
                            BookId = "3f6a29a0-526c-4caf-bad1-33a16c9e855e",
                            Description = "Book 25",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "3e443101-e583-408a-adf9-f3b6c54be9ef",
                            BookId = "5f4b30be-e72d-41df-9499-de6d8643a6c8",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/book-29.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "db762a5f-6714-4331-961f-6fb647f75cb9",
                            BookId = "5f4b30be-e72d-41df-9499-de6d8643a6c8",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "4657832b-b213-4ab0-bdcc-78cd27731438",
                            BookId = "5f4b30be-e72d-41df-9499-de6d8643a6c8",
                            Description = "Book 29",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "02da123b-5e3f-4f15-b103-8fb54762a527",
                            BookId = "aa0cd836-05a5-4258-bcba-3726828b4a3e",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/book-33.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "59ccbd16-b793-4b25-a86e-049449fbc57c",
                            BookId = "aa0cd836-05a5-4258-bcba-3726828b4a3e",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "8855d54b-b6b8-497c-bcc4-12009918bd63",
                            BookId = "aa0cd836-05a5-4258-bcba-3726828b4a3e",
                            Description = "Book 33",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "08fd2102-2aa7-465f-94c5-89c596fca30a",
                            BookId = "0218d7f0-e96a-453c-a817-b23c0c69de06",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/book-37.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "e9f7600e-7d19-49e7-8ac0-759693ed3898",
                            BookId = "0218d7f0-e96a-453c-a817-b23c0c69de06",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "4b32c7dc-b18e-4f5f-8ed5-560375114da4",
                            BookId = "0218d7f0-e96a-453c-a817-b23c0c69de06",
                            Description = "Book 37",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "d7f8282d-2cb1-4649-9720-0f0a1f7cc2a9",
                            BookId = "cac93b25-95b7-4f1f-8544-df67b563220e",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/book-41.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "8568ca2b-35c7-461d-a22d-628b20d8ea8e",
                            BookId = "cac93b25-95b7-4f1f-8544-df67b563220e",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "2f1d91ad-90c7-4df8-9a56-d7100e3938f6",
                            BookId = "cac93b25-95b7-4f1f-8544-df67b563220e",
                            Description = "Book 41",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "2cab7192-2135-40d0-97aa-b1acc6f286c5",
                            BookId = "73fd7b5f-5725-4998-91cf-48a7dc9fe7b7",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/book-45.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "2b1c3f2f-380a-4d73-a334-c6ea1e30c0ea",
                            BookId = "73fd7b5f-5725-4998-91cf-48a7dc9fe7b7",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "8b5b6cd1-1194-4f35-aa64-e6d225ee79e4",
                            BookId = "73fd7b5f-5725-4998-91cf-48a7dc9fe7b7",
                            Description = "Book 45",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "feb83f10-20fd-4662-86a4-7cabd8126a7d",
                            BookId = "a2cb72af-b919-4489-939f-813aab6b997d",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/book-49.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "f5bda504-4081-4a4b-84c6-807a4a49e722",
                            BookId = "a2cb72af-b919-4489-939f-813aab6b997d",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "90bb8fdb-5f3d-4c22-b4ae-0ca8fb7218c5",
                            BookId = "a2cb72af-b919-4489-939f-813aab6b997d",
                            Description = "Book 49",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "d2a865ca-a9bd-45ee-862e-6d6aeacca4a6",
                            BookId = "abb2e9e0-18ba-49cd-b914-a6fb2527e923",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/book-53.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "77b1986d-40b7-4b57-99d9-def1dd30dcdc",
                            BookId = "abb2e9e0-18ba-49cd-b914-a6fb2527e923",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "0b5c94ca-b05d-47cd-b4f0-4e59ac90fbf4",
                            BookId = "abb2e9e0-18ba-49cd-b914-a6fb2527e923",
                            Description = "Book 53",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "1ecf5f1e-3cd2-4747-bad4-c54348c2134b",
                            BookId = "03c1b820-6a10-4581-9225-b34670b457e6",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/book-57.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "8a334463-b68d-40ff-b57b-cd629f99bcdb",
                            BookId = "03c1b820-6a10-4581-9225-b34670b457e6",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "e7f6132d-f35f-469a-b434-947320e4c89e",
                            BookId = "03c1b820-6a10-4581-9225-b34670b457e6",
                            Description = "Book 57",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "dd859019-21cb-43de-84a4-c63f35622a6f",
                            BookId = "c29c34e8-43ef-4ca4-8df3-39329d3fd6ae",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/book-61.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "ce27520f-95d3-41f3-abd2-e8e6720ffa32",
                            BookId = "c29c34e8-43ef-4ca4-8df3-39329d3fd6ae",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "b6c5fb7f-2396-4526-8d46-1fbd6c662db2",
                            BookId = "c29c34e8-43ef-4ca4-8df3-39329d3fd6ae",
                            Description = "Book 61",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "557fad04-64bd-40d9-a7c8-758fb64062b7",
                            BookId = "279353e2-537e-4270-93e8-9e7dbd3cac01",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/book-65.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "6cb78115-3d8a-45a5-842b-c81a8361652b",
                            BookId = "279353e2-537e-4270-93e8-9e7dbd3cac01",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "7045f170-fa73-4bf0-af6a-6dccc25d3c99",
                            BookId = "279353e2-537e-4270-93e8-9e7dbd3cac01",
                            Description = "Book 65",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "a78bf8b0-d60f-47fc-ab3f-c0dc0fbdaefd",
                            BookId = "69c7a1f8-528d-473f-a17f-f77c52ee5599",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/book-69.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "caec7b87-f612-4d24-8344-81e52b304b22",
                            BookId = "69c7a1f8-528d-473f-a17f-f77c52ee5599",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "14aa3afd-fef1-4871-bc19-d31017f7a609",
                            BookId = "69c7a1f8-528d-473f-a17f-f77c52ee5599",
                            Description = "Book 69",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "d8315bd1-c3d5-4b18-bce4-8067652d8dec",
                            BookId = "7756e85e-2db5-4873-aff1-a0219598f7da",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/book-73.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "63512fae-d3ca-4c74-87ea-0651ba3aa2c4",
                            BookId = "7756e85e-2db5-4873-aff1-a0219598f7da",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "dbd2735e-b561-4878-9a19-d859ff5ab82f",
                            BookId = "7756e85e-2db5-4873-aff1-a0219598f7da",
                            Description = "Book 73",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "c0fcf458-c07b-48ce-98e8-b223fb48faf2",
                            BookId = "7c59ec68-05fd-401d-be98-d32de44f8060",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/book-77.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "8be28420-10d3-46fa-996b-27cfee42b929",
                            BookId = "7c59ec68-05fd-401d-be98-d32de44f8060",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "cebfc859-1e45-4ece-859d-767c299f6382",
                            BookId = "7c59ec68-05fd-401d-be98-d32de44f8060",
                            Description = "Book 77",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "8f892936-7fbf-4fae-b265-79cde2d39a19",
                            BookId = "5b31c3e2-7d50-4da1-9bbc-973ed735b814",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/book-81.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "fb654acb-37c5-4c90-a8b7-93b060552055",
                            BookId = "5b31c3e2-7d50-4da1-9bbc-973ed735b814",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "da079c1d-0c9c-4d86-96ea-14a3e6566adb",
                            BookId = "5b31c3e2-7d50-4da1-9bbc-973ed735b814",
                            Description = "Book 81",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "f031a0d9-5401-403b-9337-aba94be04002",
                            BookId = "c1b3a3a8-5cfd-4d58-bb65-fa046de6ba8d",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/book-85.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "703714d5-aad8-4e14-92e6-f92f5e47a7d6",
                            BookId = "c1b3a3a8-5cfd-4d58-bb65-fa046de6ba8d",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "390baec4-b1de-4d28-b207-008bb56bb31f",
                            BookId = "c1b3a3a8-5cfd-4d58-bb65-fa046de6ba8d",
                            Description = "Book 85",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        },
                        new
                        {
                            Id = "f744486d-2ac4-4e7b-8604-08d2c5bd3c77",
                            BookId = "366edef8-a08b-474f-9d8e-0136b409d0c6",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/book-89.jpg",
                            Sort = 1
                        },
                        new
                        {
                            Id = "24543996-284a-4709-98df-5c6bff763f14",
                            BookId = "366edef8-a08b-474f-9d8e-0136b409d0c6",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/product2.jpg",
                            Sort = 2
                        },
                        new
                        {
                            Id = "66fe2066-dedc-499d-8779-88dcc9bfba17",
                            BookId = "366edef8-a08b-474f-9d8e-0136b409d0c6",
                            Description = "Book 89",
                            ImgPath = "/MyStaticFiles/images/product3.jpg",
                            Sort = 3
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Discount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = "73f7641a-231e-4e2d-9f6b-7100815363ee",
                            Name = "Default",
                            Value = 0
                        },
                        new
                        {
                            Id = "fa7462f3-33db-4a0e-999f-554500271d85",
                            Name = "Test",
                            Value = 10
                        });
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.OrderDetail", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("BookId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("BookId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Book", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Discount", "Discount")
                        .WithMany("Books")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.BookImage", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany("Images")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.Order", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Discount", "Discount")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountId");

                    b.HasOne("NetCoreBookStore.Data.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCoreBookStore.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetCoreBookStore.Data.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("NetCoreBookStore.Data.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");
                });
#pragma warning restore 612, 618
        }
    }
}
